import { PERIMETER_ROLES } from "@root/service/core/security/auth/config";

export enum ASSIGNABLE_PERIMETER_ROLE {
  PERIMETER_MANAGER = PERIMETER_ROLES.PERIMETER_MANAGER,
  PERIMETER_COLLABORATOR = PERIMETER_ROLES.PERIMETER_COLLABORATOR,
  PERIMETER_CONTRIBUTOR = PERIMETER_ROLES.PERIMETER_CONTRIBUTOR,
}

export function toPerimeterRole(
  role: ASSIGNABLE_PERIMETER_ROLE | undefined
): PERIMETER_ROLES {
  switch (role) {
    case ASSIGNABLE_PERIMETER_ROLE.PERIMETER_MANAGER:
      return PERIMETER_ROLES.PERIMETER_MANAGER;
    case ASSIGNABLE_PERIMETER_ROLE.PERIMETER_COLLABORATOR:
      return PERIMETER_ROLES.PERIMETER_COLLABORATOR;
    case ASSIGNABLE_PERIMETER_ROLE.PERIMETER_CONTRIBUTOR:
      return PERIMETER_ROLES.PERIMETER_CONTRIBUTOR;
    default:
      return PERIMETER_ROLES.PERIMETER_ANONYMOUS;
  }
}
